<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BDF.M365.Diagnostic.Core\BDF.M365.Diagnostic.Core.csproj" />
    <ProjectReference Include="..\BDF.M365.Diagnostic.Office\BDF.M365.Diagnostic.Office.csproj" />
    <ProjectReference Include="..\BDF.M365.Diagnostic.Entra\BDF.M365.Diagnostic.Entra.csproj" />
    <ProjectReference Include="..\BDF.M365.Diagnostic.GitHub\BDF.M365.Diagnostic.GitHub.csproj" />
    <ProjectReference Include="..\BDF.M365.Diagnostic.Reporting\BDF.M365.Diagnostic.Reporting.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
